version: "3.9"  # optional since v1.27.0
services:
  bash:
    image: bash
    tty: true
    stdin_open: true
  # mc:
  #   image: itzg/minecraft-server
  #   environment:
  #     - EULA=true
  #   tty: true
